### ISSUE TITLE
CUDA device returns black image

### ISSUE THREAD

**Issue by zhouxian** [sxysxy/OIDN-python#3]
Hi, thank you for the amazing library! I am trying to use cuda backend `oidn.NewDevice(3)` in the cornell box example, but it returns black images. Any idea what the problem might be?

Also a quick question, do you know where I can find pre-compiled oidn executables so that i can call is via `os.system` in python?

Thanks!

**Comment by zhouxian** [comment]
Also, the pythonic way doesn't work: oidn.Device() seems not exist

**Comment by sxysxy** [comment]
OK. I guess the cause for returning black images is due to mismatched CUDA compute capability. This requires to recompile the Intel OIDN library with GPU code compatible with your GPU architecture. 

oidn.Device was introduced in oidn-python 0.4, this version is not published on PyPI. You can install the lateste version from the source, by cloning this repository and run 

```
pip install ./
```

I am busy at work. When I have time, I will try to perfect it.

**Comment by zhouxian** [comment]
got it thanks!
